export { default as Navbar } from './navbar/Navbar';
export { default as LandingPage } from './landingpage/LandingPage';
export { default as Header } from './header/Header';
export { default as Socials } from './socials/Socials';
export { default as AboutUs } from './about-us/AboutUs';
export { default as PersonCard } from './person-card/PersonCard';
export { default as CardFlipper } from './card-flipper/CardFlipper';
export { default as ScrollButton } from './scroll-button/ScrollButton';
export { default as Carousel } from './carousel/Carousel.js'
export { default as Gallery } from './gallery/Gallery.js'